In [2]:
from matplotlib import pyplot as plt
from PIL import Image
import numpy as np
import PIL.ImageOps
import csv
import zipfile
import os
import cv2
import pandas as pd


In [5]:
# dir_path = "/content/drive/MyDrive/malaria_project/landcover_cropped_with_confi_2010_2018_size10andGreater/"
dir_path = "landcover_1992onwards_min5examined_cropped_17x17"

# output_folder = "/content/drive/MyDrive/malaria_project/landcover_one_hot_cropped_with_confi_2010_2018_size10andGreater/"
output_folder = "landcover_1992onwards_min5examined_cropped_17x17_oneHotEncoded"


In [6]:
for i, file in enumerate(os.listdir(dir_path)):
    print(i, "/", len(os.listdir(dir_path)))
    if file == ".DS_Store" or file == ".ipynb_checkpoints":
        continue
    # if i < 2630:
    #   continue
    img = Image.open(dir_path + "/" + file)

    #convert to onehot image with 38 channels, one for each land cover class
    # print(img)
    arr = np.array(img)
    # print(arr)

    '''
	stuff to search:
	one hot encode input image
	categorical matrix into one-hot encoded images
	rgb segmentation masks to classes tensorflow
	CategoryEncoding keras make 3d encoding
	'''

    value_list = [0, 10, 11, 12, 20, 30, 40, 50, 60, 61, 62,
                  70, 71, 72, 80, 81, 82, 90, 100, 110,
                  120, 121, 122, 130, 140, 150, 151, 152, 153, 160, 170, 180,
                  190, 200, 201, 202, 210, 220]
    # print(len(value_list))

    one_hot_tensor = np.zeros((17, 17, 38))

    a = np.where(arr == 10)
    # print(a)
    for i, val in enumerate(value_list):
        indx = np.where(arr == val)
        one_hot_tensor[:, :, i] = arr
        # print( one_hot_tensor[:,:,i])
        one_hot_tensor[:, :, i][one_hot_tensor[:, :, i] == val] = 1
        one_hot_tensor[:, :, i][one_hot_tensor[:, :, i] != 1] = 0
        # print( one_hot_tensor[:,:,i])



    # print(one_hot_tensor.shape)

    # print(one_hot_tensor[:,:,5])
    # print(one_hot_tensor[:,:,6])

    #save image to folder
    file_wo = file.split('.')[0]
    np.save(output_folder + "/" + file_wo + '.npy', one_hot_tensor)


0 / 21212
1 / 21212
2 / 21212
3 / 21212
4 / 21212
5 / 21212
6 / 21212
7 / 21212
8 / 21212
9 / 21212
10 / 21212
11 / 21212
12 / 21212
13 / 21212
14 / 21212
15 / 21212
16 / 21212
17 / 21212
18 / 21212
19 / 21212
20 / 21212
21 / 21212
22 / 21212
23 / 21212
24 / 21212
25 / 21212
26 / 21212
27 / 21212
28 / 21212
29 / 21212
30 / 21212
31 / 21212
32 / 21212
33 / 21212
34 / 21212
35 / 21212
36 / 21212
37 / 21212
38 / 21212
39 / 21212
40 / 21212
41 / 21212
42 / 21212
43 / 21212
44 / 21212
45 / 21212
46 / 21212
47 / 21212
48 / 21212
49 / 21212
50 / 21212
51 / 21212
52 / 21212
53 / 21212
54 / 21212
55 / 21212
56 / 21212
57 / 21212
58 / 21212
59 / 21212
60 / 21212
61 / 21212
62 / 21212
63 / 21212
64 / 21212
65 / 21212
66 / 21212
67 / 21212
68 / 21212
69 / 21212
70 / 21212
71 / 21212
72 / 21212
73 / 21212
74 / 21212
75 / 21212
76 / 21212
77 / 21212
78 / 21212
79 / 21212
80 / 21212
81 / 21212
82 / 21212
83 / 21212
84 / 21212
85 / 21212
86 / 21212
87 / 21212
88 / 21212
89 / 21212
90 / 21212
91 / 2121

In [ ]:
data = np.load(
    '/content/drive/MyDrive/malaria_project/landcover_one_hot_cropped_with_confi_2010_2018_size10andGreater/3080.npy')
print(data.shape)
print(data)
print(data[:, :, 1])

(8, 8, 38)
[[[0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  ...
  [0. 1. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]

 [[0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  ...
  [0. 1. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]

 [[0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  ...
  [0. 1. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 1. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  ...
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  ...
  [0. 0. 1. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]]]

In [ ]:
l = []

# os.remove(output_folder + "102 (1).tiff")
for i, file in enumerate(os.listdir(output_folder)):
    if file == ".DS_Store" or file == ".ipynb_checkpoints" or file == "1021 (1).tiff":
        print(file)
        continue
    l.append(int(file.split(".")[0]))
    # l.append(i)

print(min(l), max(l))
s = set(l)
print("ssssssss", len(s))
print(len(l))

print(l)



0 9825
ssssssss 9826
9826
[5317, 5319, 5324, 5320, 5322, 5316, 5315, 5323, 5318, 5331, 5327, 5325, 5332, 5326, 5328, 5330, 5329, 5338, 5335, 5341, 5339, 5342, 5337, 5336, 5333, 5334, 5340, 5347, 5346, 5350, 5351, 5349, 5348, 5343, 5344, 5345, 5358, 5354, 5353, 5359, 5356, 5352, 5357, 5355, 5361, 5360, 5367, 5364, 5368, 5366, 5363, 5362, 5365, 5373, 5374, 5375, 5372, 5370, 5371, 5369, 5376, 5384, 5380, 5378, 5381, 5383, 5385, 5377, 5382, 5379, 5392, 5388, 5386, 5394, 5387, 5390, 5391, 5389, 5393, 5395, 5403, 5396, 5402, 5399, 5400, 5397, 5398, 5401, 5412, 5408, 5404, 5405, 5406, 5407, 5409, 5410, 5411, 5413, 5416, 5419, 5417, 5414, 5418, 5415, 5423, 5420, 5424, 5425, 5422, 5426, 5421, 5427, 5431, 5432, 5428, 5429, 5434, 5433, 5430, 5435, 5441, 5442, 5439, 5444, 5440, 5437, 5436, 5443, 5438, 5449, 5446, 5447, 5450, 5448, 5445, 5451, 5452, 5456, 5459, 5455, 5458, 5457, 5453, 5461, 5460, 5454, 5463, 5467, 5462, 5468, 5465, 5470, 5469, 5464, 5466, 5476, 5474, 5475, 5473, 5477, 5479, 5472, 5

In [8]:
!pip install split-folders --quiet


[notice] A new release of pip is available: 23.0 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:


import splitfolders

input_folder =  "outerfolder_landcover_1992onwards_min5examined_cropped_17x17_oneHotEncoded"
splitted_folder = "landcover_splitFolders_1992onwards_min5examined_cropped_17x17_oneHotEncoded"
splitfolders.ratio(input_folder, output=splitted_folder,
    seed=1337, ratio=(.7, .2, .1), group_prefix=None, move=False) # (train:validation:test)